package com.io.reset;

import java.io.File;

public class DeleteFile {
    public static void main(String[] args) {
        File profileFolder = new File("./MyProfile");
        File profileFile = new File(profileFolder, "profile.txt");
        profileFile.delete();
        profileFolder.delete();
        System.out.println("If the file was generated by the program then it would be deleted");
    }
}
