package com.io;

import java.io.*;

public class Main {
    public static void main(String[] args) {
        File profileFolder = new File("MyProfile");
        profileFolder.mkdir();
        File profileFile = new File(profileFolder, "profile.txt");

        try {
            profileFile.createNewFile();
            FileWriter profileWriter = new FileWriter(profileFile, false);
            profileWriter.write("----------------------------------\nHello, Welcome to my profile, My name is Hardeek and I am a Java Developer \n");
            profileWriter.write("My github profile : https://github.com/Hardeek-Simform \n\n");
            profileWriter.write("----------------------------------\nThis file is generated by the java Program");
            profileWriter.flush();
            profileWriter.close();
            BufferedReader profileReader = new BufferedReader(new FileReader(profileFile));
            String readLine = profileReader.readLine();
            System.out.println("Here below is the file content:");
            while (readLine != null) {
                System.out.print(readLine + "\n");
                readLine = profileReader.readLine();
            }
            profileReader.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}